# Numpy Library Introduction


NumPy, short for Numerical Python, has long been a cornerstone of numerical computing
In Python. It provides the data structures, algorithms, and library glue needed
For most scientific applications involving numerical data in Python. NumPy contains,
among other things:



# Numpy Arrays

In [2]:
import numpy as np

my_list = [1,2,3]

In [3]:
#creating a basic python list and then assigning it to the array() function in numpy
#this is what converts the list into an array

#This is casting a python list in the array
arr = np.array(my_list)

arr

array([1, 2, 3])

In [4]:
# Casting list of lists
#This is a python in built display


mat = [[1,2,3],[4567,89,1234],[368,73,57]]
mat

[[1, 2, 3], [4567, 89, 1234], [368, 73, 57]]

In [5]:
#casting this list of list to numpy array
#Numpy built in

np.array(mat)

#the o/p will be in the form of  2D array

array([[   1,    2,    3],
       [4567,   89, 1234],
       [ 368,   73,   57]])

In [6]:
#using numpy's own generation method to actually create arrays

#arange() is similiar to python's range() function

#arange(start, stop, step)    note: stop is not including

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
#To get specific arrays

np.zeros((3,3)) # for 2-D array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# need to pass a tuple and not a list
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# linspace() 
# this function of np allows you to get evenly spaced numbers between a certain range

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
#creating identity matrix using numpy

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Creating an array of random numbers


np.random.rand(5)

array([0.92894525, 0.01270043, 0.26869953, 0.64090624, 0.05312636])

In [13]:
#Incase you want a matrix just pass in the integers as arguments not in the form of tuples

#The function rand() will display numbers from a uniform distribution

#random.rand(columns, rows)

np.random.rand(3,5)

array([[0.20864794, 0.92090524, 0.45034983, 0.74946777, 0.55063196],
       [0.82613011, 0.02873657, 0.39009163, 0.22650175, 0.88194238],
       [0.00405451, 0.72697154, 0.1761314 , 0.56511196, 0.75858117]])

In [14]:
#To display no's from Standard Normal Distribution/Gaussion distribution

np.random.randn(2,5)

array([[-0.03089365,  0.87793391, -1.21348238,  0.33649926,  0.82181334],
       [-0.53907913, -0.12391064,  0.73624732, -0.17134337,  0.062954  ]])

In [20]:
# To generate random integers between any 2 no's use randint()

ranarr  = np.random.randint(0,100,25)
ranarr

array([90, 47, 91, 46, 25, 90, 90, 83, 13, 53, 83, 35, 17, 89, 11, 29, 97,
        9, 27, 89, 70,  0, 45, 73, 72])

In [21]:
#Reshape method

#reshape(rows,columns)....... We willl get an error if we cannot fill in completely

ranarr.reshape(5,5)

array([[90, 47, 91, 46, 25],
       [90, 90, 83, 13, 53],
       [83, 35, 17, 89, 11],
       [29, 97,  9, 27, 89],
       [70,  0, 45, 73, 72]])

In [22]:
ranarr

array([90, 47, 91, 46, 25, 90, 90, 83, 13, 53, 83, 35, 17, 89, 11, 29, 97,
        9, 27, 89, 70,  0, 45, 73, 72])

In [23]:
#Finding max value in array

#Similiarly min() for minimum value

ranarr.max()

97

In [25]:
#To find the index value of the max value in our array.

ranarr.argmax()

16

In [26]:
#To find the index value of the min value in our array.

ranarr.argmin()

21

In [29]:
#To get the shape of the array use the shape() function.

ranarr.shape

#The below O/p shows us that the array is one dimensional 

(25,)

In [31]:
#Now to reshape the same array we need to use the reshape() function
# reshape(column, row)

ranarr = ranarr.reshape(5,5)
ranarr

#Notice that the array has been resized to a 5x5 matrix

array([[90, 47, 91, 46, 25],
       [90, 90, 83, 13, 53],
       [83, 35, 17, 89, 11],
       [29, 97,  9, 27, 89],
       [70,  0, 45, 73, 72]])

In [33]:
#To check data type of any array, just use the dtype function

ranarr.dtype

dtype('int32')

#  NUMPY Indexing and Selection

In [38]:

arr = np.arange(0,31,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [39]:
#To get any element at a particular index just type the array name and the index inside[]

arr[3]

6

In [41]:
#To get a range of elements from an array, use the slicing like in python

arr[3:7]

array([ 6,  8, 10, 12])

In [42]:
#If we want everything upto a certain index, we can just put in the ending index value

arr[ : 8]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [43]:
#If we want to get all elements till a certain element, do the following
#Specify only first index : 

arr[9:]

array([18, 20, 22, 24, 26, 28, 30])

In [44]:
#Numpy arrays are differnet than Python arrays because of their ability to broad cast

arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30])

In [46]:
#Copy() function copies the whole array to a differnt array

c_arr = arr.copy()
c_arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30])

# Indexing a 2D Array or Matrix

In [50]:
#Creating a 2D Array

arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
#Fetching values from 2D arrays

# array_name[row][column]...... Note: Array indexing for rows and column starts from 0

arr2d[0][1]

#Above will return array from column with index 0 and row with index 1

10

In [61]:
# to get the whole row 
arr2d[0]

array([ 5, 10, 15])

In [62]:
#Below is the single bracket notation
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
#array_name[row,column]

arr2d[1,2]

30

# Important

In [66]:
#USe the Slice notation to grab few other values from the matrix
#Suppose we want to gerab 10,15 and 25,30

arr2d[ :2,1: ]

array([[10, 15],
       [25, 30]])

In [67]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [71]:
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

# Conditional Selection

In [73]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
#Compare the array with any integer to get a boolean array

bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
#We can use the boolean array to do conditional selection

arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [80]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [81]:
#Example all elements of array less than 3

arr[arr<3]

array([1, 2])