# Numpy Arrays

In [4]:
# Create a list 

my_list = [1,2,3]

In [3]:
import numpy as np

In [3]:
# Cast the list in the array() function

arr = np.array(my_list)

#It returns an array
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

print(my_mat)

# The below is a list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:

np.array(my_mat)

#the below is an array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# This is Python's built in range function
# np.arange(start,stop,step)

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# Get an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [9]:
# np.zeros ((noofmatrices,rows,columns))
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2,5,5), dtype = 'int32')

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [11]:
# If we want arrays of one's
np.ones((2,6,4), dtype = 'int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [12]:
# linspace will return an array of 10 evenly spaced points 
# liinspace(start, stop, no_of_points)

np.linspace(0,5,10)



array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
# Generating random number of points in a given range

np.linspace(0,10, 20)  # Getting 20 points


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [14]:
# Creating an identity matrix using Numpy

np.eye(4)

#Identity matrix is a 2D square matrix where no fo rows = no of columns and diagonal of ones

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Numpy to create arrays of random numbers

#Method 1 : rand()

np.random.rand(5)  # need to pass in a single digit

array([0.56943742, 0.94850379, 0.89112382, 0.30162014, 0.40438893])

In [40]:
# Generating random 5x5 marix of numbers

np.random.rand(5,5)

# 2D matrix

array([[0.48596127, 0.73048786, 0.4869782 , 0.7012878 , 0.95149391],
       [0.5605078 , 0.30057585, 0.98641703, 0.96058484, 0.93396961],
       [0.85737325, 0.10051969, 0.02046275, 0.01723499, 0.89015097],
       [0.66052977, 0.54949236, 0.91596632, 0.59602312, 0.37899384],
       [0.01051718, 0.69780247, 0.46158546, 0.34493898, 0.52976217]])

In [43]:
# If we want to return a sample from Gaussion Distribution

np.random.randn(2)


# This will return values from normal distribution rather than from a uniform distribution

array([-1.55809116, -0.50774291])

In [16]:
# Getting a random integer

np.random.randint(1,100)

29

In [17]:
# Getting random integers in a range
# np.random.randint(range_start, range_end, no_of_integers)

np.random.randint(1,100,10)

array([50, 30, 70, 61, 59, 70, 62, 65, 35, 60])

# Array Function

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr = np.random.randint(0,50,10)

In [21]:
ranarr

array([27, 29, 20, 31, 10, 26, 49, 43, 31,  0])

In [22]:
# Reshape Method
# It will return an array with the same data but a new shape

arr.reshape(5,5)   # Reashaping as 5x5 array 
    

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
# An error will be given if we are not able to fill the matrix completely

# Example:

arr.reshape(4,4)

# Look below

NameError: name 'arr' is not defined

In [25]:
# Let's check ranarr

ranarr

array([27, 29, 20, 31, 10, 26, 49, 43, 31,  0])

In [28]:
ranarr.max() # Max value in the array

49

In [29]:
ranarr.min()

0

In [30]:
# To find the index value i.e. the location where the manx or the min element is in

ranarr.argmax()

6

In [31]:
ranarr.argmin()

9

In [34]:
# Shape of the vector

arr.shape

# It is a 1D vector

(25,)

In [35]:
# Lets reshape it

arr = arr.reshape(5,5)

In [36]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.shape

# It is 2D now


(5, 5)

# Data Type in Array

In [41]:
arr.dtype

# It is a 32 bit integer

dtype('int32')

In [42]:
 # If we  don not want ot typle np.random.randn or rand int()
# We can import the function from the package

In [43]:
from numpy.random import randint

In [46]:
randint(2,10,6)  # Just give a reference to self

array([9, 3, 7, 8, 7, 8])

# Numpy Array Indexing and Selection

In [47]:
import numpy as np

In [50]:
# Creating an array from 0 to 10
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[8]   # This will return value at index position 8


8

In [54]:
# TO get values in array we can use slice notation

arr[1:5]  # All the values from index 1 to index 5(not including 5)

array([1, 2, 3, 4])

In [56]:
arr[0:5]  #All the values from index 0 to 5 not including 5

array([0, 1, 2, 3, 4])

In [58]:
# To get everything in the array

arr[ : 6]

array([0, 1, 2, 3, 4, 5])

In [61]:
arr[ 2: ] # start at a praticular index and get everything in the array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# Numpy list differentiate from Python list because of their ability to broadcast

# Example

arr[0:5] = 100  # It is going to broadcast the value '100' to all the index postion specified

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr = np.arange(0,11)  # Resetting the array

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
slice_of_arr = arr[0: 6]  # Creating a new array and assigning it values by slicing the main array i.e arr

In [96]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [97]:
slice_of_arr[:]  #Grabbing everything in the array

array([0, 1, 2, 3, 4, 5])

In [98]:
# Broadcasting this array

slice_of_arr[:] = 99

In [99]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [100]:
# When we call our original array
# We can see that 99 is broadcasted on that too

arr

# The reason numpy does that is to avoind memeory issues. It is not going to automatically set copies of arrays

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [101]:
arr = np.arange(0,11)  # resetting

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
 # How to avoid it?
# We need to specifically copy the array

arr_copy = arr.copy()

arr_copy


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Idexing a 2D array/ Matrix

In [5]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [6]:
# Double bracket notation

# Lets say we are grabbing no 5

arr_2d[0]

# This will index entire row

array([ 5, 10, 15])

In [7]:
# array_name[row_index_no][column_index_no]

arr_2d[0][1]

# returns a particular number in the matrix

10

In [8]:
# Let's grab the no 40

arr_2d[2][1]

40

In [9]:
# Single Bracket Notation

arr_2d[2,1]

40

In [10]:
# Grabbing a series from the top of the array

arr_2d[ : 2, 1: ]  # Grab everything upto row 2 and then grab from column 1 onwards

array([[10, 15],
       [25, 30]])

In [11]:
# So the syntax is 
# array_name[no of rows slice, no of columns slice]

# Example:

arr_2d[ : 2]  # Get all the elemnts from row0 to row2 excluding the second row

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arr_2d[ 1: , 0: ] 

array([[20, 25, 30],
       [35, 40, 45]])

 # Conditional Selection

In [19]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Comparing the array ot get a boolean array

arr > 5

# It will return true where the comparisono meets and 'false' where it does not meet

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
# Let's create a boolean array to do conditional selection on it

bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
arr[bool_arr]

# We are using the 'bool_arr' to condition or idex elements from the 'arr' array

# It will only return the elements where the condition > 5

array([ 6,  7,  8,  9, 10])

In [32]:
# Elements less than 3

arr[arr<3]

array([1, 2])

In [33]:
arr_2d = np.arange(50).reshape(5,10)

In [34]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
# Grabbing the middle elements 13,14 and 23,24

arr_2d[ 1:3, 3: 5]

array([[13, 14],
       [23, 24]])

# Numpy Operations

In [53]:
arr = np.arange(0,11)  # Creating an array

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Adding 2 arrays on element to element basis

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [55]:
# Same for subtraction and multiplication

In [57]:
# SAme can be done on the scaler operation

arr + 100

# Here Numpy would broadcast +100 to every element in the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [59]:
# Sometimes numpy will give a warning instead of an error

arr/ arr

# Here 0/0 does not make sense here it gave us 'nan'

<ipython-input-59-3a8b1f03fa0a>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/ arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [60]:
# SAme for below

1/arr

# inf is infinity

<ipython-input-60-88e676e67d74>:3: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [61]:
# Taking square root of every element in the array

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [62]:
# for Exponenetial

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [64]:
# Finding the max and min value

np.max(arr)

10

In [65]:
# It can also do trignometric functions

np.log(arr)

<ipython-input-65-faaf5afdc5c9>:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])