# Python NumPy

Numpy means numerical Python.
It is a powerful Python library for fast 1D, 2D, 3D arrays processing

It is faster than list bacuse it uses list types
Numpy uses 32bit vs List which uses inbuilt type which is int

Numpy uses contiguous memory and list uses scattered memory



Numpy comes across as a mathematical library. Scipy is powerful than numpy.
It is like a MATLAB Replacement

Images can be stored using numpy.
It is pretty extenively used in ML applications. Tenserflow is like Numpy library

In [1]:
#Importing the Numpy Library

import numpy as np


# The Basics

In [3]:
# How to initialize an array in numpy:

a = np.array([1,2,3])

print(a)

[1 2 3]


In [7]:
# BElow we are creating a list within a list. it is basically a 2D array

#It is floating point array

b = np.array([[9.23,243.132,45.32],[3.5,6.8,23.0]])

print(b)

[[  9.23  243.132  45.32 ]
 [  3.5     6.8    23.   ]]


In [8]:
# Getting the dimension of numpy array

a.ndim

1

In [9]:
b.ndim

2

In [10]:
# Get Shape
a.shape


(3,)

In [11]:
b.shape

(2, 3)

In [12]:
# Get type of numpy array

a.dtype

dtype('int32')

In [13]:
# Get size

a.itemsize

4

# Accessing/Changing specific elements,rows,columns, etc.

In [15]:
# We are decalring a 2x7 array

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# Get shape

a.shape

(2, 7)

In [20]:
# Get a specific element in the array

# we will use the row, column notation [r,c]
# Example we want ot get the elemt '13'
# It's location is on column2, element 5 as python indexing starts at 0, the following will be used

a[1,5]

13

In [22]:
# Get a specific row

a[0, :]      #Same syntax like slicing a list

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [26]:
# Getting elemnts after a certain interval

#[startindex:endindex:stepsize]
# Syntx is : [row/column index, startindex:endindex:stepsize]

a[0,1:6:2]


array([2, 4, 6])

In [29]:
# Change any number in the array

# Example we will change the element 13 in the array

a[1,5] = 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [30]:
# We want to replace a whole column

a[:,2] = 99

print(a)

[[ 1  2 99  4  5  6  7]
 [ 8  9 99 11 12 20 14]]


In [31]:
# IF we want to add different elemnts

a[:,2] = [99, 100]

print(a)

[[  1   2  99   4   5   6   7]
 [  8   9 100  11  12  20  14]]


# A 3D Example

In [37]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
# Get specific element
# try work outside in

#Suppose we want the element 4

b[0,1,1]


4

In [44]:
# Replacing values

b[:,1,:] = [[9,9],[8,8]]

In [46]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initialize different types of array

In [49]:
# All 0's Matrix
# There is a nice built in function called np.zeros()

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# or we can do the following

np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [52]:
# All one's matrix

np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [53]:
# Intitialize a matrix thats not zeros or ones

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [56]:
# Any other (full_like)

np.full_like(a,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [59]:
# Intialize a array and matrix of random numbers

np.random.rand(4,2,3)

array([[[0.76121309, 0.5915544 , 0.13655553],
        [0.65662265, 0.34116275, 0.67715768]],

       [[0.05386666, 0.59629822, 0.47141363],
        [0.7012179 , 0.09433023, 0.72456635]],

       [[0.95882732, 0.83809915, 0.69020254],
        [0.34948444, 0.07106187, 0.48186337]],

       [[0.17646246, 0.4087255 , 0.00759861],
        [0.44016   , 0.79319677, 0.08272967]]])

In [63]:
# Random decimal numbers

np.random.random_sample(a.shape)

array([[0.74682069, 0.95955676, 0.511285  , 0.00348021, 0.61950886,
        0.2619154 , 0.13567451],
       [0.80217575, 0.77808268, 0.81609563, 0.60605911, 0.18197793,
        0.60824836, 0.26618968]])

In [67]:
# Random Integer Values
# np.random.randint(endpoint, size = (rows,columns))

np.random.randint(7, size = (3,3))

array([[5, 1, 3],
       [0, 2, 2],
       [0, 6, 3]])

In [70]:
np.random.randint(4,11, size = (4,6))

#Excluding 10

array([[ 9,  5, 10,  9,  8,  9],
       [ 8, 10,  5,  5,  8, 10],
       [10,  7, 10, 10,  9,  9],
       [ 5,  4,  6,  8,  8, 10]])

In [71]:
# Identity Matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
# Repeat an array 4 times

arr = np.array([[1,2,3]])

r1 = np.repeat(arr,4,axis = 0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


# ----

In [80]:
o = np.ones((5,5))

o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
z = np.zeros((3,3))
z[1,1] = 9     # Filling out the middle element with a 9
print(z)



[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


#

In [89]:
o[1:4,1:4] = z

print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# ------------------------------------------

In [92]:
a = np.array([1,2,3])

b = a

In [93]:
print(b)

[1 2 3]


In [94]:
b[0]  =100

In [95]:
a

array([100,   2,   3])

# Maths in Numpy

In [102]:
# IT supports element wise addition, Subtraction.

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [103]:
a + 2

array([3, 4, 5, 6])

In [104]:
a -2

array([-1,  0,  1,  2])

In [105]:
a * 2

array([2, 4, 6, 8])

In [106]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [107]:
b = np.array([1,0,1,0])
a + b   # here we are doing element wise multiplication

array([2, 2, 4, 4])

In [108]:
# Geometrical functions on a numpy array
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [109]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear algebra type stuff

In [110]:
a = np.ones((2,3))

print(a)

b = np.full((3,2),2)

print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [112]:
# Numpy has a matrix multiplication function

#  matmul(matrix1, matrix2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [114]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [116]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.min(stats,axis = 1) # This is on row basis

# The o/p is min of the first row, min of second row

array([1, 4])

In [120]:
np.max(stats, axis = 1)

array([3, 6])

In [121]:
np.sum(stats, axis = 0)

# this will add all the columns going downwards

array([5, 7, 9])

# Reorganizing Arrays

In [123]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [126]:
after = before.reshape((8,1)) # reshaping it to 8x1 matrix

In [127]:
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [129]:
# Vertically stacking vector

v1 = np.array([1,2,3,4])

v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

# This will make it part of same matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
# Horizontal Stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

# This has horizontally stacked it all

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Load data from file

In [135]:
# If we do not want to use the pandas to get the data we can also use numpy

 #    np.genfromtxt('data.txt', delimiter = ',')
    
# We use the genfromtxt function and specify the delimiter

In [136]:
# astype() this function  transfers it to the different data type
